### ISSUE TITLE
angular 1.6.3 breaks batarang

### ISSUE THREAD

**Issue by ygilliot** [angular/batarang#307]
Enabling batarang while working with angular 1.6.3 totally breaks the application to watch.
I don't know why, it's working fine in 1.6.2. I use angular via cdn but i don't think the problem comes from that.

Could someone investigate, if project is still alive? thanks.

Here is what chrome's console outputs:

> Uncaught TypeError: ac(...).info is not a function
>     at Ce (angular.js:2793)
>     at angular.js:33194
>     at angular.js:6
> Ce @ angular.js:2793
> (anonymous) @ angular.js:33194
> (anonymous) @ angular.js:6
> 
> angular-sanitize.js:555Uncaught TypeError: f.module(...).provider(...).info is not a function
>     at angular-sanitize.js:555
>     at angular-sanitize.js:6
> (anonymous) @ angular-sanitize.js:555
> (anonymous) @ angular-sanitize.js:6
> 
> angular-messages.js:267Uncaught TypeError: l.module(...).info is not a function
>     at angular-messages.js:267
>     at angular-messages.js:6
> (anonymous) @ angular-messages.js:267
> (anonymous) @ angular-messages.js:6
> 
> angular-cookies.js:24Uncaught TypeError: c.module(...).info is not a function
>     at angular-cookies.js:24
>     at angular-cookies.js:6
> (anonymous) @ angular-cookies.js:24
> (anonymous) @ angular-cookies.js:6
> 
> angular.js:38Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.6.3/$injector/modulerr?p0=ng&p1=Error%3A%20%5…udflare.com%2Fajax%2Flibs%2Fangular.js%2F1.6.3%2Fangular.min.js%3A22%3A277)
>     at angular.js:38
>     at angular.js:4920
>     at p (angular.js:402)
>     at g (angular.js:4880)
>     at eb (angular.js:4802)
>     at c (angular.js:1909)
>     at Object.Pc.ea.resumeBootstrap (angular.js:1938)
>     at maybeBootstrap (hint.js:569)

**Comment by ocombe** [comment]
As far as I know this is no longer maintained, it was @btford's project and he left google a year ago...

**Comment by gkalpak** [comment]
Sorry, I haven't given batarang much love lately :grin:
We should definitely fix this issue, though. I'll look into it this week.

**Comment by ygilliot** [comment]
Great! as far as I know, there's no better chrome extension for Angular 1 apps. It would be awful if support stops at 1.6

**Comment by MustafaSange** [comment]
Same here downloaded Batarang and it's not working.  Hope it will be fixed soon.

**Comment by gary-b** [comment]
Last I heard, there was no one to handle releases to the chrome web store. Do we have someone now?

**Comment by gkalpak** [comment]
We have me :smiley:
I would like to merge angular/angular-hint#122 and angular/angular-hint#123 before cutting a new release. I hope to get it out early next week.

**Comment by gkalpak** [comment]
_Update_
angular/angular-hint#123 is in.
I have a better alternative to #122 (correctly detecting _and_tracking watched one-time expressions): angular/angular-hint#124

Once #124 is in (hopefully this week), we can cut the release.

**Comment by gkalpak** [comment]
0.10.8 is out, but it's broken. Tracking in #310.
